/*
 * Copyright (c) 2024 by Brendan Haran, All Rights Reserved.
 * Use of this file or any of its contents is strictly prohibited without prior written permission from Brendan Haran.
 * Current File (firebase_options.dart) Last Modified on 9/13/24, 10:45 AM
 *
 */

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDBtHZPXoWlaOPMDZZNK2DDu78QDtlEeg',
    appId: '1:836962932399:web:cf85818b068b9cf4ca265a',
    messagingSenderId: '836962932399',
    projectId: 'mathmatchup',
    authDomain: 'mathmatchup.firebaseapp.com',
    storageBucket: 'mathmatchup.appspot.com',
    measurementId: 'G-VD5WSCQL39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoau7nljzlZAnmVY7kz2Yx6JlO31VIBCE',
    appId: '1:836962932399:android:9bdfe58dc4203326ca265a',
    messagingSenderId: '836962932399',
    projectId: 'mathmatchup',
    storageBucket: 'mathmatchup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0a34P-2mwIH6GVz67Kxr3s-rIHDpCbEs',
    appId: '1:836962932399:ios:21e71a9278b094a8ca265a',
    messagingSenderId: '836962932399',
    projectId: 'mathmatchup',
    storageBucket: 'mathmatchup.appspot.com',
    iosClientId: '836962932399-qs26428u5o01v4lq58jglrh1r79abn67.apps.googleusercontent.com',
    iosBundleId: 'com.brendanharan.mathMatchup',
  );
}
